baseURL = "https://peekbyte.github.io/peekbyte-site/"
title = "Peekbyte - Hassan Falahi"
theme = "peekbyte"
publishDir = "docs"
# If not set, it will not appear. Otherwise it will show below your footer links
copyright = "(c) 2018 - 2018 Hassan Falahi -- All rights reserved."


[params]
  # Enables syntax highlighting
  highlight = true 
  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim"]
  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Hassan Falahi"
  github = "peekbyte"
  email = "me@peekbyte.com"
  gaid = "Your Google Analytics ID"
  twitter = "peekbyte"
